name: actions-workflow-examples
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  COMMIT_SHA: ${{ github.sha }}
  EVENT_NAME: ${{ github.event.name }}
  GITHUB_TOKEN: ${{ github.token }}
  ISSUE_URL: ${{ github.event.issue.html_url }}
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Actions Example
        uses: actions/checkout@v3
      - run: echo "Hello World"
      - name: Comment PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: thollander/actions-comment-pull-request@v1
        id: build-finish
        with:
          message: |
            Build Success, Commit hash ${{env.COMMIT_SHA}}
          pr_number: ${{ github.event.number }}
          reactions: eyes, rocket
      - name: Finish Message
        id: finish-message
        run: |
          echo "message=Deploy hash ${COMMIT_SHA:0:7} Token ${EVENT_NAME} ISSUE ${ISSUE_URL}"
      - name: Build Message
        run: if [ $? -eq 0 ]; then echo "Build success!"; else exit 1; fi


